- SeaPublicWebsite/ExternalServices/OpenEPCApi.cs
Test: on local environment
Risk: minimal, essentially a typo
Documentation: none required
> seabeta-266-incorrect-return-value-from-getconstructionagebandfromepc

- SeaPublicWebsite.UnitTests/ResetUnusedFieldsTests.cs
- SeaPublicWebsite/Controllers/EnergyEfficiencyController.cs
- SeaPublicWebsite/Helpers/UserDataHelper.cs
- SeaPublicWebsite/Services/QuestionFlowService.cs
From a design perspective, whenever an UserDataModel field is updated I call the ResetUnusedFields method to set to 'null' fields that became unreachable.
> Seabeta 274 reset contradictory fields

- SeaPublicWebsite/Models/EnergyEfficiency/HeatingPatternViewModel.cs
- SeaPublicWebsite/Models/EnergyEfficiency/HomeAgeViewModel.cs
- SeaPublicWebsite/Models/EnergyEfficiency/NumberOfOccupantsViewModel.cs
- SeaPublicWebsite/Models/EnergyEfficiency/TemperatureViewModel.cs
- SeaPublicWebsite/Startup.cs
Whenever we are asking a user for numeric or date inputs we should use the GovUK databinding attributes to make sure that the generated error messages fit the GovUk guidelines.
> fix: Use GovUk data binders where appropriate

- README.md
- SeaPublicWebsite/Program.cs
Running migrations on app start up is not normally considered best practice (Microsoft have some reasons here: https://docs.microsoft.com/en-us/ef/core/managing-schemas/migrations/applying?tabs=dotnet-core-cli#apply-migrations-at-runtime). However on GOV.PaaS I think that it's actually a reasonable way to do it compared to the alternatives.
Objections and counter arguments:
- If multiple instances of your application are running, both applications could attempt to apply the migration concurrently and fail (or worse, cause data corruption).
- We ensure that only instance 0 runs the migrations
- Similarly, if an application is accessing the database while another application migrates it, this can cause severe issues.
- We want to aim for 100% uptime so there will always be code accessing …
> seabeta-283 Running migrations on GOV.PaaS

- SeaPublicWebsite.BusinessLogic/Models/Epc.cs
- SeaPublicWebsite.Data/Migrations/20220614163252_AddDedicatedPrimaryKeyToEpcTable.Designer.cs
- SeaPublicWebsite.Data/Migrations/20220614163252_AddDedicatedPrimaryKeyToEpcTable.cs
The issue was that EF Core had taken the `EpcId` column as the primary key and so disallowed multiple rows for the same EPC
> fix: Allow multiple property details to use the same EPC

- SeaPublicWebsite/Services/RecommendationService.cs
Checked this with Joanna as a sensible assumption. Also tested that it does indeed fix the issue
> fix: Stop getting loft insulation recommendation when there is no loft

- SeaPublicWebsite/Controllers/EnergyEfficiencyController.cs
- SeaPublicWebsite/ExternalServices/PostcodesIo/PostcodesIoApi.cs
- SeaPublicWebsite/Startup.cs
In general we shouldn't stop user's entering their postcodes if postcodes.io falls over.
This is especially true for the load test
> feat: Log postcode errors and allow user to continue

- SeaPublicWebsite/Program.cs
- SeaPublicWebsite/Startup.cs
tested locally
minimal risk - this change is only cosmetic as far as I can see from the relevant docs
no documentation required
> feat: name antiforgery token explicitly and hide kestrel header

- SeaPublicWebsite/apt.yml
- SeaPublicWebsite/manifest.yml
This is, I think, the right way to do this. CloudFoundry's apt buildpack is apparently "experimental" but it's been around for 6 years and is still maintained. All it does is install the dependencies you list in `apt.yml`.
> BEISSEA-67 Use CloudFoundry's apt buildpack to install Chrome's dependencies when an instance starts

- Dockerfile
- SeaPublicWebsite/SeaPublicWebsite.csproj
- SeaPublicWebsite/Services/EnergyEfficiency/PdfGeneration/PdfGenerationService.cs
Three key things here:
* We now install Chrome in Docker, not in .NET
* Chrome needs to be installed in the image we actually run .NET from, not the build image (this took me the longest to work out)
* Our old method for getting the local address started returning `http://[::]:80` which Chrome doesn't recognise as a valid address, so I've hardcoded it. I'm not very happy about doing that but since everything's in Docker the address should always be the same.
> BEISSEA-NONE Move Chrome installation to base image instead of build image

- SeaPublicWebsite.BusinessLogic/ExternalServices/Bre/RecommendationService.cs
- SeaPublicWebsite.BusinessLogic/Models/Enums/YearBuilt.cs
- SeaPublicWebsite.BusinessLogic/Models/PropertyData.cs
- SeaPublicWebsite.BusinessLogic/PropertyDataUpdater.cs
- SeaPublicWebsite.UnitTests/BusinessLogic/Models/PropertyDataTests.cs
- SeaPublicWebsite/Views/EnergyEfficiency/ActionPlan/ActionPlanWithDiscardedRecommendations.cshtml
- SeaPublicWebsite/Views/EnergyEfficiency/ActionPlan/ActionPlanWithMaybeRecommendations.cshtml
- SeaPublicWebsite/Views/EnergyEfficiency/ActionPlan/ActionPlanWithSavedRecommendations.cshtml
- SeaPublicWebsite/Views/EnergyEfficiency/CavityWallsInsulated.cshtml
- SeaPublicWebsite/Views/EnergyEfficiency/HomeAge.cshtml
This is a reworking of https://github.com/UKGovernmentBEIS/beis-simple-energy-advice-beta/pull/259.
The main difference is that we preserve the deprecated home age bands to support historic data.
> PC-572: Update home age options to match EPC bands

- README.md
Updated README.md to change references to old name of project (IYPEE) to current (SEA)
> PC-NONE: Updated references to old name of project in readme

- SeaPublicWebsite.UnitTests/CookieServiceTests.cs
We deliberately don't cover all test cases - they're split across three tests. Hopefully this will save someone a little time in rediscovering this in future!
n/a
> PC-NONE: Add comments to clarify expected test behaviour

- .github/workflows/build-and-run-tests.yml
- Dockerfile
- SeaPublicWebsite.BusinessLogic/SeaPublicWebsite.BusinessLogic.csproj
- SeaPublicWebsite.Data/SeaPublicWebsite.Data.csproj
- SeaPublicWebsite.UnitTests/SeaPublicWebsite.UnitTests.csproj
- SeaPublicWebsite/SeaPublicWebsite.csproj
- SeaPublicWebsite/Services/EnergyEfficiency/PdfGeneration/PdfGenerationService.cs
- docker-compose.yml
- global.json
[Link to Jira ticket](https://beisdigital.atlassian.net/browse/PC-1122)
- Updating C# from 10 to 11
- Updating .Net from 6 to 8
- Changing all references from old versions to new versions
- Breaking change in .Net 8 requires references to port 80 to become port 8080.
- Updated SDK version in global.json from 5.0 -> 8.0
- Some additional warnings in editor (115 warnings to 150)
> PC-1122: Investigation into updating C# & .NET versions

- .github/workflows/build-and-run-tests.yml
- Dockerfile
- SeaPublicWebsite.BusinessLogic/SeaPublicWebsite.BusinessLogic.csproj
- SeaPublicWebsite.Data/Migrations/20220609164007_Initial.Designer.cs
- SeaPublicWebsite.Data/Migrations/20220609164007_Initial.cs
- SeaPublicWebsite.Data/SeaPublicWebsite.Data.csproj
- SeaPublicWebsite.UnitTests/SeaPublicWebsite.UnitTests.csproj
- SeaPublicWebsite/Middleware/BasicAuthMiddleware.cs
- SeaPublicWebsite/Middleware/SecurityHeadersMiddleware.cs
- SeaPublicWebsite/SeaPublicWebsite.csproj
- SeaPublicWebsite/Services/EnergyEfficiency/PdfGeneration/PdfGenerationService.cs
- docker-compose.yml
- global.json
[Link to Jira ticket](https://beisdigital.atlassian.net/browse/PC-1050)
C# & .NET update changes with port number 8080 reverted to 80
> Pc 1122 investigation into c# and .net update

- .github/workflows/build-and-run-tests.yml
- Dockerfile
- SeaPublicWebsite.BusinessLogic/SeaPublicWebsite.BusinessLogic.csproj
- SeaPublicWebsite.Data/Migrations/20220609164007_initial.Designer.cs
- SeaPublicWebsite.Data/Migrations/20220609164007_initial.cs
- SeaPublicWebsite.Data/SeaPublicWebsite.Data.csproj
- SeaPublicWebsite.UnitTests/SeaPublicWebsite.UnitTests.csproj
- SeaPublicWebsite/Middleware/BasicAuthMiddleware.cs
- SeaPublicWebsite/Middleware/SecurityHeadersMiddleware.cs
- SeaPublicWebsite/SeaPublicWebsite.csproj
- docker-compose.yml
- global.json
Reverts UKGovernmentBEIS/beis-simple-energy-advice-beta#293
> Revert "Pc 1122 investigation into c# and .net update"

- SeaPublicWebsite.Data/Migrations/20240806095041_ForwardFillTimestamps.cs
Add comment explaining the issue we found and our process to clean up.
n/a
> PC-NONE: Explain migration cleanup process

- SeaPublicWebsite/compile-sass-and-js.js
now refers to build output from net8.0
> PC-NONE: bump net version in compile js script

- Dockerfile
- SeaPublicWebsite/Controllers/HomeController.cs
- docker-compose.yml
Similar to how we have on WH:LG now, to get it off my to-do list
> Redirect base URL to start page when running locally

- .github/dependabot.yml
[Link to Jira ticket](https://beisdigital.atlassian.net/browse/PC-1636)
fixes dependabot.yml
adds an important newline
specify npm grouping correctly
set large max pull requests limit
> PC-1636: fix dependabot.yml

- .github/workflows/build-and-run-tests.yml
see https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/
> PC-NONE: Bump upload-artifacts to v4

- SeaPublicWebsite/Views/EnergyEfficiency/YourRecommendations.cshtml
[Link to Jira ticket](https://beisdigital.atlassian.net/browse/PC-1714)
[Link to Jira ticket](https://beisdigital.atlassian.net/browse/PC-1715)
this option being true, in combination with no `Text` property being set was causes an empty `<h1>` to be placed onto the page
double checked, the rest of the legends in the project seem to be set correctly
> PC-1714 PC-1715: Fix incorrect IsPageHeading option

- SeaPublicWebsite/Resources/SharedResources.cy.resx
- SeaPublicWebsite/Resources/SharedResources.resx
- SeaPublicWebsite/Views/EnergyEfficiency/ActionPlan/Partials/_AvailableSchemesOrGrants.cshtml
As this is an immediate release, this PR is made directly to staging so that it can be QAed in isolation of other changes already merged to dev
[Link to Jira ticket](https://beisdigital.atlassian.net/browse/PC-1706)
removes HUG2 reference from the final page discussing other available grants
also adds a missing full stop
> PC-1706: Remove reference to Home Upgrade Grant (staging)

- SeaPublicWebsite/Views/EnergyEfficiency/ActionPlan/ActionPlanWithDiscardedRecommendations.cshtml
- SeaPublicWebsite/Views/EnergyEfficiency/ActionPlan/ActionPlanWithMaybeRecommendations.cshtml
- SeaPublicWebsite/Views/EnergyEfficiency/ActionPlan/ActionPlanWithSavedRecommendations.cshtml
- SeaPublicWebsite/Views/EnergyEfficiency/Recommendations/RecommendationsPdf.cshtml
[Link to Jira ticket](https://beisdigital.atlassian.net/browse/PC-1718)
All the action plan views
The recommendations pdf view also needed a title
I double checked and the website title is persistent in the downloaded PDF, so setting the titles in the view does work
> PC-1718: Add titles to missing pages

- SeaPublicWebsite/Views/EnergyEfficiency/ActionPlan/ActionPlanWithSavedRecommendations.cshtml
[Link to Jira ticket](https://beisdigital.atlassian.net/browse/PC-1729)
Added hidden text to each link to give further context for screenreader users, to aid with seemingly multiple identical links.
> PC-1729: Multiple Instances of Identical Link Text 

- SeaPublicWebsite/wwwroot/css/_simple-energy-advice-custom.scss
[Link to Jira ticket](https://beisdigital.atlassian.net/browse/PC-1722)
sets default text colour and padding for button text
this is to override the apple defaults (white text and 1em padding)
with white text the button is invisible
> PC-1722: Fix User Cannot See the Selected Language in the Language Options

- SeaPublicWebsite/Views/Shared/_Layout.cshtml
[Link to Jira ticket](https://beisdigital.atlassian.net/browse/PC-1753)
Page language identifier shows current culture's ISO code, instead of just "en"
> PC-1753: Make page language identifier adapt to current culture

- SeaPublicWebsite/Resources/SharedResources.cy.resx
- SeaPublicWebsite/Resources/SharedResources.resx
- SeaPublicWebsite/Views/EnergyEfficiency/ActionPlan/Partials/_ReturnToActionPlan.cshtml
- SeaPublicWebsite/Views/EnergyEfficiency/NewOrReturningUser.cshtml
- SeaPublicWebsite/Views/EnergyEfficiency/Recommendations/Partials/_FloorInsulationSuspendedFloor.cshtml
- SeaPublicWebsite/Views/EnergyEfficiency/Recommendations/Partials/_WhatYouCouldSave.cshtml
- SeaPublicWebsite/Views/EnergyEfficiency/YourRecommendations.cshtml
[Link to Jira ticket](https://beisdigital.atlassian.net/browse/PC-1731)
Replace b and non-specific span tags throughout the app
Note GDS does not explicitly recommend using the strong tag, prefering the use of the `govuk-!-font-weight-bold` class. Where no classes are specified, I've added the GDS one to ensure semantic HTML and correct styling
> PC-1731: Fix variations in text conveying information

- SeaPublicWebsite.UnitTests/SeaPublicWebsite.UnitTests.csproj
- SeaPublicWebsite/Program.cs
- SeaPublicWebsite/SeaPublicWebsite.csproj
[Link to Jira ticket](https://beisdigital.atlassian.net/browse/PC-1686)
removes dependencies that are not currently used in FWTS
one log enricher to remove, but [documentation](https://www.nuget.org/packages/serilog.enrichers.environment) suggests that it adds a `{MachineName}` template to our log format. we use the default log format so this is unused
> PC-1686: Remove Unused Dependencies

- .github/dependabot.yml
[Link to Jira ticket](https://beisdigital.atlassian.net/browse/PC-1686)
specifically in nuget * must be used instead of x, see [docs](https://docs.github.com/en/code-security/dependabot/working-with-dependabot/dependabot-options-reference#versions-ignore)
> PC-1686: Fix FluentAssertions ignore version

- SeaPublicWebsite/Resources/SharedResources.cy.resx
- SeaPublicWebsite/Resources/SharedResources.resx
- SeaPublicWebsite/Views/EnergyEfficiency/ActionPlan/Partials/_AvailableSchemesOrGrants.cshtml
[Link to Jira ticket](https://beisdigital.atlassian.net/browse/PC-1832)
- Updated broken OFGEM link destination for “helpful guides” to OFGEM environmental & social schemes [page](https://www.ofgem.gov.uk/environmental-and-social-schemes)
- Corrected link styling to GDS accessibility standard
> PC-1832: Change broken link URL to OFGEM schemes page

- .github/dependabot.yml
[Link to Jira ticket](https://beisdigital.atlassian.net/browse/PC-1860)
use x over * in ignored dependency versions
it seems to be suggested that this is how GitHub intends you to do these ignored versions, though neither * or x have worked so far.
porting this from WH:LG so the spec is at least consistent between projects
> PC-1860: Update ignored dependency specification

- SeaPublicWebsite/Resources/SharedResources.cy.resx
- SeaPublicWebsite/Resources/SharedResources.resx
- SeaPublicWebsite/Views/EnergyEfficiency/ActionPlan/ActionPlanWithDiscardedRecommendations.cshtml
- SeaPublicWebsite/Views/EnergyEfficiency/ActionPlan/ActionPlanWithMaybeRecommendations.cshtml
- SeaPublicWebsite/Views/EnergyEfficiency/ActionPlan/ActionPlanWithSavedRecommendations.cshtml
- SeaPublicWebsite/Views/EnergyEfficiency/NoRecommendations.cshtml
[Link to Jira ticket](https://beisdigital.atlassian.net/browse/PC-1868)
- Updated "Help for household" link text translation (added to scope of this work as per client instruction [here](https://beisdigital.atlassian.net/browse/PC-1868?focusedCommentId=96382))
- Updated "learn about energy labels" link
- Text updated to make it clear user is going to Energy Saving Trust
- Translation in Cymraeg added
> PC-1868: Update broken energy label link

- LICENCE
[Link to Jira ticket](https://beisdigital.atlassian.net/browse/PC-1873)
adds an MIT licence to our project, as specified by GDS https://gds-way.digital.cabinet-office.gov.uk/manuals/licensing.html
uses 2022 for start copyright year as this is date of the project start
> PC-1873: Add MIT licence

- Dockerfile
install node before copying files in Dockerfile
ensures that this step can be correctly cached & doesn't re-run on any file changes in the project
helps out local dev build times
> PC-NONE: Slight optimisation to Dockerfile during local dev

- Dockerfile
[Link to Jira ticket](https://beisdigital.atlassian.net/browse/PC-2016)
to 139.0.7258.138-1
restructures install code a little to allow for this. we can't use version= syntax as google remove old versions from the PPA repository very quickly so the install will fail as the old version cannot be found. downloads the .deb install file instead manually and installs that which seems to be more stable
> PC-2016: Pin google chrome version

- README.md
would be nice to have the configuration committed to the project as code but for now can specify this in the README
> PC-NONE: Specify Build: Always on the docker compose configuration
