UKGovernmentBEIS/beis-simple-energy-advice-beta

- SeaPublicWebsite/Views/EnergyEfficiency/AnswerSummary.cshtml
Test: on local environment
Risk: minimal, essentially a typo
Documentation: none required
> seabeta-267-null-coalescing-bug

- .github/workflows/build-and-deploy-to-gov-paas-dev.yml
- .github/workflows/build-and-deploy-to-gov-paas-usertesting.yml
- .gitignore
- Infrastructure/LoginToGovPaasTemplate.sh
- Infrastructure/SetEnvironmentSecretsTemplate.sh
- README.md
- SeaPublicWebsite/ExternalServices/EpbEpcApi.cs
- SeaPublicWebsite/Helpers/Global.cs
- SeaPublicWebsite/Views/Shared/_Layout.cshtml
- SimpleEnergyAdvice.sln
Some small tidy ups to help with Beta deployment, and a start on documentation in the Readme
> Seabeta 189 beta deployment

- SeaPublicWebsite/Views/EnergyEfficiency/AnswerSummary.cshtml
The loft insulation question only appears if the loft is accessible. The issue was in the view.
> Seabeta 254 insulated roof null exception

- .github/workflows/_build-and-deploy-to-gov-paas.yml
- Infrastructure/CreateEnvironment.sh
- Infrastructure/SetEnvironmentSecretsTemplate.sh
Switch over to a `beta` space and start using two app instances in parallel
Also configures the correct logit instance for the beta
> feat: update infrastructure scripts to use beta space

- SeaPublicWebsite/Views/Shared/_Layout.cshtml
Only code change needed is adding the gtag in the \<head\>. The rest is handled in google analytics 4.
> Add google analytics

- SeaPublicWebsite/Views/EnergyEfficiency/AnswerSummary.cshtml
Branch created before merging 273 (back and forward button refactor), so all 'change =' places will be replaced with 'entryPoint =' after merging.
Also the git diff is not too nice, since I've moved all the body of the page in the 'rows' variable.
> Seabeta 323 answer summary list component

- Infrastructure/Metrics/Grafana/Conf/custom.ini
- Infrastructure/Metrics/Grafana/Conf/defaults.ini
- Infrastructure/Metrics/Grafana/manifest.yml
- Infrastructure/Metrics/Grafana/runtime.txt
- Infrastructure/Metrics/PrometheusServer/manifest.yml
- Infrastructure/Metrics/PrometheusServer/prometheus.yml
- Infrastructure/Metrics/README.md
- SeaPublicWebsite/Controllers/HomeController.cs
- SimpleEnergyAdvice.sln
Add code for setting up metrics monitoring and temporary page that always throws an exception to test alerting.
> Seabeta 192 metrics

- SeaPublicWebsite.UnitTests/BreApi.cs
- SeaPublicWebsite.UnitTests/QuestionFlowServiceTests.cs
- SeaPublicWebsite/DataModels/UserDataModel.cs
- SeaPublicWebsite/ExternalServices/Bre/BreRequest.cs
- SeaPublicWebsite/ExternalServices/Bre/Enums/BreHeatingPatternType.cs
- SeaPublicWebsite/Models/EnergyEfficiency/HeatingPatternViewModel.cs
- SeaPublicWebsite/Services/RecommendationService.cs
- SeaPublicWebsite/Views/EnergyEfficiency/HeatingPattern.cshtml
Tests: tested locally
Risk: minimal as change is small and this PR only adds a new request parameter in the same format as other previously working parameters
Documentation: only one comment added for assumption made, no other necessary
> Seabeta 389 add off hours to request

- SeaPublicWebsite/Startup.cs
Set up the database connection when running on GOV.PaaS
> feat: Connect to database on GOV.PaaS

- .github/workflows/_build-and-deploy-to-gov-paas.yml
- Infrastructure/CreateEnvironment.sh
- SeaPublicWebsite.Data/Migrations/20220613161206_UpdateLodgementDateColumn.Designer.cs
- SeaPublicWebsite.Data/Migrations/20220613161206_UpdateLodgementDateColumn.cs
- SeaPublicWebsite.Data/Migrations/20220613161525_AddDataProtection.Designer.cs
- SeaPublicWebsite.Data/Migrations/20220613161525_AddDataProtection.cs
- SeaPublicWebsite.Data/SeaDbContext.cs
- SeaPublicWebsite.Data/SeaPublicWebsite.Data.csproj
- SeaPublicWebsite/Controllers/EnergyEfficiencyController.cs
- SeaPublicWebsite/SeaPublicWebsite.csproj
- SeaPublicWebsite/Startup.cs
We need this to use form anti-forgery across multiple servers
> Configure data protection

- SeaPublicWebsite/ExternalServices/Bre/BreRequest.cs
Agree with BRE + energy savings trust
> feat: remove 3 unwanted recommendations

- .github/workflows/build-and-deploy-to-gov-paas-production.yml
- Infrastructure/CreateEnvironment.sh
- SimpleEnergyAdvice.sln
Scripts to create and deploy the prod environment
> Seabeta 311 prod environment

- SeaPublicWebsite/Views/EnergyEfficiency/Recommendations/HotWaterCylinderInsulation.cshtml
- SeaPublicWebsite/Views/EnergyEfficiency/YourSavedRecommendations.cshtml
tested: locally
risk: minimal
docs: none required
> feat: add copy to YourSavedRecommendations.cshtml and typo fix

- SeaPublicWebsite/Views/EnergyEfficiency/Index.cshtml
- SeaPublicWebsite/Views/Error/PageNotFound.cshtml
- SeaPublicWebsite/Views/Feedback/FeedbackForm.cshtml
- SeaPublicWebsite/Views/Feedback/FeedbackSurvey.cshtml
Normally I don't like commenting out code, but this will need to be reinstated very soon so it seems appropriate in this case.
> feat: Remove phone number from site

- SeaPublicWebsite/Constants.cs
- SeaPublicWebsite/ExternalServices/EmailSending/GovUkNotifyApi.cs
- SeaPublicWebsite/ExternalServices/EmailSending/GovUkNotifyConfiguration.cs
- SeaPublicWebsite/ExternalServices/EmailSending/IEmailSender.cs
- SeaPublicWebsite/appsettings.Production.json
- SeaPublicWebsite/appsettings.json
Make email links point to the right place
> fix: Fix up email links

- SeaPublicWebsite/ExternalServices/Bre/BreRequest.cs
- SeaPublicWebsite/Services/RecommendationService.cs
> feat: make floortype nullable

- SeaPublicWebsite/Views/EnergyEfficiency/Index.cshtml
tested locally
minimal risk
only docs required are commented section to be added later (as part of seabeta-555)
> feat: update homepage design

- SeaPublicWebsite.BusinessLogic/Models/Enums/RoofConstruction.cs
> feat: add yes or no to answers for roof flat q

- SeaPublicWebsite/Views/EnergyEfficiency/NoRecommendations.cshtml
> Seabeta 605 ofgem guide in 0 recommendations

- SeaPublicWebsite/ExternalServices/EpbEpc/EpbEpcApi.cs
Double checked the logic with joanna
> Seabeta 612 Update logic for roof insulation epc

- .github/workflows/delete-old-data.yml
- SeaPublicWebsite.BusinessLogic/Models/PropertyData.cs
- SeaPublicWebsite.Data/DataAccessProvider.cs
- SeaPublicWebsite.DeleteOldData/Program.cs
- SeaPublicWebsite.DeleteOldData/SeaPublicWebsite.DeleteOldData.csproj
- SimpleEnergyAdvice.sln
This and the next few following merges to this branch are for testing cf tasks triggered by gh actions to run a data deletion project
> Seabeta 342 delete old data

- SeaPublicWebsite/Views/EnergyEfficiency/ActionPlan/ActionPlanWithSavedRecommendations.cshtml
- SeaPublicWebsite/wwwroot/css/_simple-energy-advice-custom.scss
> Seabeta 617 recomm table mobile

- SeaPublicWebsite/Views/EnergyEfficiency/ActionPlan/ActionPlanWithSavedRecommendations.cshtml
- SeaPublicWebsite/wwwroot/css/_simple-energy-advice-custom.scss
remove legacy nowrap
tested - works for desktop view and doesn't affect mobile view
low risk - css only
> feat: remove nowrap

- SeaPublicWebsite/Views/EnergyEfficiency/Index.cshtml
- SeaPublicWebsite/Views/Error/PageNotFound.cshtml
> feat: unhide phone numbers

- SeaPublicWebsite/Views/EnergyEfficiency/ActionPlan/Partials/_ReturnToActionPlan.cshtml
> feat: revert to old feedback styling

- SeaPublicWebsite/appsettings.json
tested locally
minimal risk
this ticket also includes wiping all private beta data from the prod db, which has been done
> feat: update cookie message version

- SeaPublicWebsite/Models/EnergyEfficiency/ActionPlanViewModel.cs
> Remove heat pump cost/savings from action plan totals

- SeaPublicWebsite/Middleware/SecurityHeadersMiddleware.cs
- SeaPublicWebsite/appsettings.json
Required for google analytics to work
Can be tidied up later as tech debt
> Allow all connect-src

- SeaPublicWebsite.BusinessLogic/ExternalServices/EpbEpc/EpbEpcDto.cs
Tested locally
Minimal risk
No docs required
> feat: allow null MainHeatingDescription

- SeaPublicWebsite/Views/EnergyEfficiency/ActionPlan/ActionPlanWithSavedRecommendations.cshtml
Tested locally
Minimal risk
No docs required
> feat: update action plan with MCS link

- SeaPublicWebsite/Views/EnergyEfficiency/YourRecommendations.cshtml
- SeaPublicWebsite/Views/Shared/_Recommendation.cshtml
Update references to energy price cap from April to October
> BEISSEA-26: Update references to energy price cap from April to October

- SeaPublicWebsite/Views/EnergyEfficiency/YourRecommendations.cshtml
- SeaPublicWebsite/Views/Shared/_Recommendation.cshtml
BEISSEA-26: Update references to energy price cap from April to October
> Beissea - updated fuel prices

- SeaPublicWebsite/appsettings.json
> Update BRE base url

- SeaPublicWebsite/appsettings.json
> GIT-NONE: revert bre base url

- SeaPublicWebsite.BusinessLogic/ExternalServices/Bre/BreApi.cs
- SeaPublicWebsite/appsettings.json
GIT-NONE: Alter BRE base API and path
> GIT-NONE: Alter BRE base API and path

- SeaPublicWebsite/appsettings.json
Reverts UKGovernmentBEIS/beis-simple-energy-advice-beta#225
> Revert "BEISSEA-NONE: Revised api url."

- SeaPublicWebsite/manifest.yml
Does what it says on the tin (I hope)
> BEISSEA-67 Increase storage size of PaaS instance

- SeaPublicWebsite/Services/EnergyEfficiency/PdfGeneration/PdfGenerationService.cs
- SeaPublicWebsite/wwwroot/css/_simple-energy-advice-custom.scss
Configures puppeeteer launch options to prevent default disabling of chrome extensions.
> Beissea 67 pdf fix branch

- SeaPublicWebsite/Middleware/BasicAuthMiddleware.cs
Merging straight to production!
> Add basic auth to 401 error page

- SeaPublicWebsite.BusinessLogic/ExternalServices/Bre/BreApi.cs
- SeaPublicWebsite.BusinessLogic/ExternalServices/Common/HttpRequestHelper.cs
- SeaPublicWebsite.BusinessLogic/ExternalServices/EpbEpc/EpbAddressDto.cs
- SeaPublicWebsite.BusinessLogic/ExternalServices/EpbEpc/EpbAssessmentsDto.cs
- SeaPublicWebsite.BusinessLogic/ExternalServices/EpbEpc/EpbEpcApi.cs
- SeaPublicWebsite.BusinessLogic/ExternalServices/EpbEpc/EpbEpcDto.cs
- SeaPublicWebsite.UnitTests/CookieServiceTests.cs
- SeaPublicWebsite.UnitTests/SeaPublicWebsite.UnitTests.csproj
- SeaPublicWebsite/ExternalServices/GoogleAnalytics/GoogleAnalyticsService.cs
- SeaPublicWebsite/ExternalServices/PostcodesIo/PostcodesIoApi.cs
- SeaPublicWebsite/Helpers/BuildNumberHelper.cs
- SeaPublicWebsite/SeaPublicWebsite.csproj
- SeaPublicWebsite/Services/Cookies/CookieService.cs
> BEISSEA-76: Prevent Test Project from being published

- SeaPublicWebsite/Startup.cs
Required by the new DESNZ platform. I don't expect you'll have any comments but thought it worth getting a second pair of eyes anyway!
This PR is set to merge into the new dev branch, and I'll also merge it into staging. That way we won't have HTTPS redirection on the branches we're testing the new platform with.
> Remove HTTPS redirection

- README.md
Merging to dev even though it's only a doc change because I don't want to trigger a release.
> Updated the release process section of the readme to reflect the new infrastructure

- SeaPublicWebsite/Views/EnergyEfficiency/YourRecommendations.cshtml
- SeaPublicWebsite/Views/Shared/_Recommendation.cshtml
- Updated copy text to reflect January 2024 estimates for cost savings.
Text in recommendations summary page:
Text beneath each recommendation:
> PC-574 Updating copy text to reflect January 2024 changes

- SeaPublicWebsite/Controllers/EnergyEfficiencyController.cs
- SeaPublicWebsite/Models/EnergyEfficiency/ActionPlanViewModel.cs
- SeaPublicWebsite/Models/EnergyEfficiency/ConfirmAddressViewModel.cs
- SeaPublicWebsite/Views/EnergyEfficiency/ActionPlan/ActionPlanWithSavedRecommendations.cshtml
- SeaPublicWebsite/Views/EnergyEfficiency/ConfirmAddress.cshtml
This fixes the issue on the confirm address page investigated as PC-841.
> PC-841: Fix view model binding by removing localizer

- SeaPublicWebsite/Resources/SharedResources.cy.resx
- SeaPublicWebsite/Resources/SharedResources.resx
closes [PC-933](https://beisdigital.atlassian.net/browse/PC-933)
changes translation keys with new provided text
> PC-933: Update Recommendations to reflect April 1 2024 Energy Price Changes

- SeaPublicWebsite/Resources/SharedResources.cy.resx
- SeaPublicWebsite/Resources/SharedResources.resx
closes [PC-933](https://beisdigital.atlassian.net/browse/PC-933)
changes translation keys with new provided text
fix two identified typos
> PC-933 update recommendations to reflect april price changes

- SeaPublicWebsite/Program.cs
Currently we're not running migrations on our deployed environments - this fixes that. It's not ideal, but mirrors what HUG2 and GBIS do. I've raised tickets to improve across all three services.
n/a
> PC-NONE: Run migrations on deployed environments

- .github/workflows/build-and-run-tests.yml
- Dockerfile
- SeaPublicWebsite.BusinessLogic/SeaPublicWebsite.BusinessLogic.csproj
- SeaPublicWebsite.Data/SeaPublicWebsite.Data.csproj
- SeaPublicWebsite.UnitTests/SeaPublicWebsite.UnitTests.csproj
- SeaPublicWebsite/SeaPublicWebsite.csproj
- SeaPublicWebsite/Services/EnergyEfficiency/PdfGeneration/PdfGenerationService.cs
- docker-compose.yml
- global.json
Reverts UKGovernmentBEIS/beis-simple-energy-advice-beta#285
> Revert "PC-1122: Investigation into updating C# & .NET versions"

- .github/workflows/build-and-run-tests.yml
- Dockerfile
- SeaPublicWebsite.BusinessLogic/SeaPublicWebsite.BusinessLogic.csproj
- SeaPublicWebsite.Data/Migrations/20220609164007_Initial.Designer.cs
- SeaPublicWebsite.Data/Migrations/20220609164007_Initial.cs
- SeaPublicWebsite.Data/SeaPublicWebsite.Data.csproj
- SeaPublicWebsite.UnitTests/SeaPublicWebsite.UnitTests.csproj
- SeaPublicWebsite/Middleware/BasicAuthMiddleware.cs
- SeaPublicWebsite/Middleware/SecurityHeadersMiddleware.cs
- SeaPublicWebsite/SeaPublicWebsite.csproj
- SeaPublicWebsite/Services/EnergyEfficiency/PdfGeneration/PdfGenerationService.cs
- SeaPublicWebsite/Services/StaticAssetsVersioningService.cs
- docker-compose.yml
- global.json
[Link to Jira ticket](https://beisdigital.atlassian.net/browse/PC-1050)
Changing cache dictionary to ConcurrentDictionary to make it thread-safe and avoid concurrency issues.
> PC:1122 investigation into c# and .net update

- SeaPublicWebsite/Resources/SharedResources.cy.resx
- SeaPublicWebsite/Resources/SharedResources.resx
[Link to Jira ticket](https://beisdigital.atlassian.net/browse/PC-934)
Updated copy text to reflect the July/Gorffennaf energy cap changes
> PC-934: Copy text changes for July price cap change

- .github/workflows/build-and-run-tests.yml
- Dockerfile
- SeaPublicWebsite.BusinessLogic/SeaPublicWebsite.BusinessLogic.csproj
- SeaPublicWebsite.Data/Migrations/20220609164007_Initial.Designer.cs
- SeaPublicWebsite.Data/Migrations/20220609164007_Initial.cs
- SeaPublicWebsite.Data/SeaPublicWebsite.Data.csproj
- SeaPublicWebsite.UnitTests/SeaPublicWebsite.UnitTests.csproj
- SeaPublicWebsite/Middleware/BasicAuthMiddleware.cs
- SeaPublicWebsite/Middleware/SecurityHeadersMiddleware.cs
- SeaPublicWebsite/SeaPublicWebsite.csproj
- SeaPublicWebsite/Services/EnergyEfficiency/PdfGeneration/PdfGenerationService.cs
- SeaPublicWebsite/Services/StaticAssetsVersioningService.cs
- docker-compose.yml
- global.json
﻿
Implementing the upgrade to C# and .Net
> PC-1050 Implementing C# and .Net upgrade

- SeaPublicWebsite/Resources/SharedResources.cy.resx
- SeaPublicWebsite/Resources/SharedResources.resx
[Link to Jira ticket](https://beisdigital.atlassian.net/browse/PC-935)
Updated text to reflect October as the latest price change.
> PC-935: Updated text to reflect October price change

- SeaPublicWebsite/Resources/SharedResources.cy.resx
- SeaPublicWebsite/Resources/SharedResources.resx
[Link to Jira ticket](https://beisdigital.atlassian.net/browse/PC-1554)
updates the copy text as prescribed by translations in the ticket
there seems to be more changes to the welsh than just the month. will defer to the provided translations than existing ones
> PC-1554: Update Recommendations to reflect Jan 2 2025 Energy Price Changes

- .github/dependabot.yml
[Link to Jira ticket](https://beisdigital.atlassian.net/browse/PC-1636)
fixes dependabot file by copying a valid one
> PC-1636: fix formatting of dependabot file

- .github/pull_request_template.md
> PC-NONE: add QA notes tick box to pull request template

- SeaPublicWebsite/Resources/SharedResources.cy.resx
- SeaPublicWebsite/Resources/SharedResources.resx
- SeaPublicWebsite/Views/EnergyEfficiency/ActionPlan/Partials/_AvailableSchemesOrGrants.cshtml
same as #355, to ensure this change exists on dev branch too
> PC-1706: Remove reference to Home Upgrade Grant (dev)

- Dockerfile
- SeaPublicWebsite/Services/EnergyEfficiency/PdfGeneration/PdfGenerationService.cs
- docker-compose.yml
[Link to Jira ticket](https://beisdigital.atlassian.net/browse/PC-1710)
in order to use sandboxed mode, we need docker to use a non root user
container is changed to now use a non root user. our external state uses the database which shouldn't be affected by a user change.
> PC-1710: Improve PDF generating method

- Dockerfile
- SeaPublicWebsite/Services/EnergyEfficiency/PdfGeneration/PdfGenerationService.cs
- docker-compose.yml
Small fix to specify container user
> PC-1760: Add container user

- SeaPublicWebsite/Services/EnergyEfficiency/PdfGeneration/PdfGenerationService.cs
Added --no-sandbox flag as a test
> PC-1710 Improve PDF generation method

- .github/dependabot.yml
[Link to Jira ticket](https://beisdigital.atlassian.net/browse/PC-1686)
ticket initially requested weekly, though as we have since agreed will not check these very often (bi monthly) it helps to set the interval large as it will group all updates in a month together
> PC-1686: Reduce dependabot scan frequency to monthly

- SeaPublicWebsite/Constants.cs
- SeaPublicWebsite/Resources/SharedResources.cy.resx
- SeaPublicWebsite/Resources/SharedResources.resx
- SeaPublicWebsite/Views/StaticPages/AccessibilityStatement.cshtml
[Link to Jira ticket](https://beisdigital.atlassian.net/browse/PC-1809)
updates accessibility page to new agreed formats
changes the accessibility keys on the page to the [new format](https://github.com/UKGovernmentBEIS/beis-simple-energy-advice-beta/blob/dev/docs/LocalisationDocumentation.md)
<details>
<summary>English</summary>
</details>
<details>
<summary>Welsh</summary>
</details>
> PC-1809: Update Accessibility Statement

- .github/dependabot.yml
[Link to Jira ticket](https://beisdigital.atlassian.net/browse/PC-1686)
aims to fix #394 not being ignored
> PC-1686: Use more expansive format for version ignoring

- SeaPublicWebsite/Resources/SharedResources.cy.resx
- SeaPublicWebsite/Resources/SharedResources.resx
[Link to Jira ticket](https://beisdigital.atlassian.net/browse/PC-1829)
Update month in copy
> PC-1829: Update Recommendations to reflect April 1 2025 Energy Price Changes

- SeaPublicWebsite/Resources/SharedResources.cy.resx
- SeaPublicWebsite/Resources/SharedResources.resx
[Link to Jira ticket](https://beisdigital.atlassian.net/browse/PC-1923)
Specify RdSAP 2012 methodology
<details>
</details>
> PC-1923: Update Recommendations text - RdSAP2012

- SeaPublicWebsite/Views/EnergyEfficiency/Recommendations/Partials/_InstallHeatPump.cshtml
- SeaPublicWebsite/Views/EnergyEfficiency/Recommendations/Partials/_ReplaceSingleGlazedWindowsWithDoubleOrTripleGlazing.cshtml
﻿[Link to Jira ticket](https://beisdigital.atlassian.net/browse/PC-1940)
- Fixed link destinations
> PC-1940: Fix broken link destinations

- SeaPublicWebsite/Views/EnergyEfficiency/Recommendations/Partials/_AddLoftInsulation.cshtml
[Link to Jira ticket](https://beisdigital.atlassian.net/browse/PC-1951)
as requested on ticket
> PC-1951: Update loft disruption category to minimal

- SeaPublicWebsite/SeaPublicWebsite.csproj
[Link to Jira ticket](https://beisdigital.atlassian.net/browse/PC-1960)
required for pdf downloads
> PC-1960: Update PuppeteerSharp

- SeaPublicWebsite/Controllers/AuthController.cs
[Link to Jira ticket](https://beisdigital.atlassian.net/browse/PC-1995)
small change to check that the dev deployment pipeline still works
should be no impact to the site
> PC-1995: Format a file

- README.md
- docs/MakingFrontendChanges.md
[Link to Jira ticket](https://beisdigital.atlassian.net/browse/PC-2003)
uses the same structure now as the WH:LG README for clarity
copy the frontend changes docs as they should equally apply for FWTS
> PC-2003: Improve README.md to WH:LG spec
